services:
  app-be:
    build:
      args:
        user: devel
        uid: 1000
      context: ./backend
      dockerfile: Dockerfile.dev
    image: news-aggregator/php8.2
    container_name: news-aggregator_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/docker/supervisorctl:/etc/supervisor/conf.d
      - ./backend/docker/php/core.ini:/usr/local/etc/php/conf.d/core.ini
    networks:
      - news-aggregator_network

  app-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: frontend-node:19-alpine
    container_name: news-aggregator_react
    working_dir: /var/www
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www
    networks:
      - news-aggregator_network

  nginx:
    image: nginx:1.23.3-alpine
    container_name: news-aggregator_nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - news-aggregator_network

  mysql:
    image: mysql:8.0.32
    container_name: news-aggregator_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: news-aggregator
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - news-aggregator_db:/var/lib/mysql-files
      - ./backend/docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - news-aggregator_network

  adminer:
    image: adminer:4.8.1-standalone
    container_name: news-aggregator_adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: news-aggregator_mysql
    ports:
      - 8001:8080
    networks:
      - news-aggregator_network

  redis:
    image: redis:7-alpine
    container_name: news-aggregator_redis
    restart: unless-stopped
    tty: true
    volumes:
      - ./redis/data:/data
    networks:
      - news-aggregator_network

networks:
  news-aggregator_network:
    driver: bridge

volumes:
  news-aggregator_db:
    driver: local
